### ISSUE TITLE
convert() header skip as default could cause issues

### ISSUE THREAD

**Issue by capsandiego** [abetomo/Convert-Athena-QueryResults-to-Array#8]
I think there is a small issue with the code.
I suppose this line is used to remove the header item from the resultSet:
```
$rows = array_slice($resultSet['Rows'], 1);
```
In case, when we have more than 1000 rows returned in the resultSet, we need to use ``` 'NextToken' ``` in the ```Client->GetQueryResults()``` call. So it means that we might want to call the ```convert()``` function many times. This way, every time we call ```convert()``` function, we miss one row.

One solution could be to call the function with an extra parameter:

```
public static function convert(array $resultSet, bool $skip_header = false): array
    {
         $offset  = $skip_header ? 1 : 0;
         $rows = array_slice($resultSet['Rows'], $offset);
       ... 
```

**Comment by abetomo** [comment]
Thanks for the suggestion.
I've added the option.
